/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberIdRouteImport } from './routes/$memberId'
import { Route as IndexRouteImport } from './routes/index'

const MemberIdRoute = MemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$memberId'
  id: '__root__' | '/' | '/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberIdRoute: typeof MemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$memberId': {
      id: '/$memberId'
      path: '/$memberId'
      fullPath: '/$memberId'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberIdRoute: MemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
